language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
before_install:
  -php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
before_script:
  -composer install
script: phpunit --configuration phpunit.xml --coverage-text